env:
  global:
    - JWT_SECRET_TOKEN=andela@sigmacool
    - NODE_ENV=test
    - DB_USERNAME=root
    - DB_PASSWORD=1234glody
    - DB_HOST=localhost
    - DB_PORT=5432
    - TEST_DATABASE=send-it-tdd
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
    - postgresql
before_script:
  - psql -c 'CREATE DATABASE sendit_test;' -U postgres
  - npm run createTables
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "765a4e4444c11aa351b8b049ab5a43b4f9da19ea40491d02009d27f31d3b89a7"