language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "5c4f62f95155c47ff22979e08e7a1753de51304f6f9b1b25071c92a19ac14839"